name: deploy myblog

on:
  push:
    branches:
      - 'main' # 针对 main 分支
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'bin/*'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # 第三的 action

      - name: set id_rsa # 设置 id_rsa
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.MY_ID_RSA}}" > ~/.ssh/id_rsa # 仓库 Settings>Actions> 添加，把本地id_rsa内容拷贝添加 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 125.124.59.115 >> ~/.ssh/known_hosts

      - name: deploy # 自动发布
        run: |
          ssh root@125.124.59.115 "
            # 注意：服务器已经 git clone 代码到 /root/myblog/imooc-320-server 目录

            cd /root/myblog/imooc-320-server;
            git checkout . ;
            git checkout main;
            git pull origin main; # 重新下载最新的代码

            # 重启服务
            npm install;
            npm run prd;
          "

      - name: delete id_rsa # 删除 id_rsa
        run: rm -rf ~/.ssh/id_rsa
